# Clippy configuration for the project

# Documentation
# ============
# Documentation lints
doc_markdown = "warn"
missing_docs = "warn"
missing_doc_code_examples = "warn"

# Style
# =====
# Style lints
blocks_in_conditions = "warn"
collapsible_if = "warn"
collapsible_else_if = "warn"
comparison_chain = "warn"
empty_line_after_outer_attr = "warn"
explicit_counter_loop = "warn"
identity_op = "warn"
if_same_then_else = "warn"
if_not_else = "warn"
items_after_statements = "warn"
len_zero = "warn"
let_and_return = "warn"
let_underscore_drop = "warn"
manual_memcpy = "warn"
manual_non_exhaustive = "warn"
manual_range_contains = "warn"
map_clone = "warn"
map_unwrap_or = "warn"
module_inception = "warn"
module_name_repetitions = "warn"
needless_borrow = "warn"
needless_continue = "warn"
needless_pass_by_value = "warn"
needless_return = "warn"
new_without_default = "warn"
new_without_default_derive = "warn"
option_map_unit_fn = "warn"
option_map_or_none = "warn"
option_unwrap_used = "warn"
ptr_arg = "warn"
range_plus_one = "warn"
range_plus_one = "warn"
redundant_closure = "warn"
redundant_closure_for_method_calls = "warn"
redundant_field_names = "warn"
redundant_pattern_matching = "warn"
redundant_static_lifetimes = "warn"
result_map_or_into_option = "warn"
result_map_unwrap_or_else = "warn"
result_unwrap_used = "warn"
same_functions_in_if_condition = "warn"
search_is_some = "warn"
should_implement_trait = "warn"
single_match_else = "warn"
string_add = "warn"
string_add_assign = "warn"
string_lit_as_bytes = "warn"
string_to_string = "warn"
type_complexity = "warn"
unimplemented = "warn"
unnecessary_unwrap = "warn"
unused_self = "warn"
useless_attribute = "warn"
useless_conversion = "warn"
useless_format = "warn"
vec_box = "warn"
vec_init_then_push = "warn"
verbose_file_reads = "warn"
verbose_bit_mask = "warn"

# Correctness
# ===========
# Correctness lints
absurd_extreme_comparisons = "warn"
assertions_on_constants = "warn"
clone_on_ref_ptr = "warn"
copy_iterator = "warn"
debug_assert_with_mut_call = "warn"
deprecated_cfg_attr = "warn"
double_parens = "warn"
drop_bounds = "warn"
drop_copy = "warn"
duplicate_underscore_argument = "warn"
empty_loop = "warn"
error_impl_error = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
float_arithmetic = "warn"
float_cmp = "warn"
float_cmp_const = "warn"
for_loops_over_fallibles = "warn"
forget_ref = "warn"
from_over_into = "warn"
if_let_some_result = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
if_let_some_result = "warn"
if_let_unnecessary_unwrap = "warn"
